# --- START OF FILE render.yaml ---

services:
  - type: web
    name: truth-social-scraper
    env: python
    plan: free
    healthCheckPath: "/"
    
    # Define a persistent disk to store the Playwright browser cache
    disks:
      - name: playwright-cache
        mountPath: /opt/render/.cache/ms-playwright
    
    # The build command is now simpler as we let Playwright manage itself
    buildCommand: "pip install -r requirements.txt && playwright install"
    
    # The start command remains the same
    startCommand: "gunicorn app:app"
    
    # Set an environment variable to tell Playwright where to find its cache
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: BOT_TOKEN
        sync: false # Set in dashboard
      - key: CHANNEL_ID
        sync: false # Set in dashboard
