# --- START OF FILE render.yaml ---
# This file is the single source of truth for your Render service.
# It installs system dependencies, sets up the build, and starts the service.

services:
  - type: web
    name: truth-social-scraper # This name will appear on your Render dashboard
    env: python
    plan: free # Ensures it uses the free tier
    
    # The build command installs Python packages and then Playwright's browsers
    buildCommand: "pip install -r requirements.txt && playwright install --with-deps"
    
    # The start command uses Gunicorn to run your Flask app
    startCommand: "gunicorn app:app"
    
    # Health check for Render to know your service is alive
    healthCheckPath: "/"
    
    # Environment variables for your secrets (set these in the Render dashboard)
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
        
    # === THE CRITICAL FIX ===
    # Pre-install the system packages that Playwright's browser needs to run
    aptPackages:
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libxss1
      - libasound2
      - libpangocairo-1.0-0
      - fonts-liberation
      - libappindicator3-1
      - lsb-release
      - libgbm-dev
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libx11-xcb1
      - libxcb-dri3-0
      - libdrm2
      - libharfbuzz-icu0
