# --- START OF FILE render.yaml ---
# This is the single source of truth for your Render service.

services:
  - type: web
    name: truth-social-scraper # You can change this name if you like
    env: python
    plan: free # Ensures it uses the free tier
    
    # Define a persistent disk to store the Playwright browser cache.
    # This is the key to fixing the "Executable doesn't exist" error.
    disks:
      - name: playwright-cache
        mountPath: /opt/render/.cache/ms-playwright
    
    # The build command installs Python packages and then Playwright's browsers.
    # The browsers will be installed onto the persistent disk defined above.
    buildCommand: "pip install -r requirements.txt && playwright install"
    
    # The start command uses Gunicorn to run your Flask app.
    startCommand: "gunicorn app:app"
    
    # Health check for Render to know your service is alive.
    healthCheckPath: "/"
    
    # Environment variables for your secrets.
    # You must still set the actual values in the Render dashboard's "Environment" tab.
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      # This explicitly tells Playwright to use the persistent disk path.
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
        
    # Pre-install the system packages to fix the "Host system is missing dependencies" warning.
    aptPackages:
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libxss1
      - libasound2
      - libpangocairo-1.0-0
      - fonts-liberation
      - libappindicator3-1
      - lsb-release
      - libgbm-dev
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libx11-xcb1
      - libxcb-dri3-0
      - libdrm2
      - libharfbuzz-icu0
