# --- START OF FILE render.yaml ---
# This is the single source of truth for your Render service.

services:
  - type: web
    name: truth-social-scraper
    env: python
    plan: free
    
    # Let Render default to using a build.sh script
    # We remove the buildCommand line from here
    
    startCommand: "gunicorn app:app"
    healthCheckPath: "/"
    
    # Define a persistent disk to store the Playwright browser cache.
    disks:
      - name: playwright-cache
        mountPath: /opt/render/.cache/ms-playwright
        
    # Environment variables for your secrets and Playwright's cache.
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
        
    # Pre-install the system packages.
    aptPackages:
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libxss1
      - libasound2
      - libpangocairo-1.0-0
      - fonts-liberation
      - libappindicator3-1
      - lsb-release
      - libgbm-dev
      - libgdk-pixbuf2.0-0
      - libgtk-3-0
      - libx11-xcb1
      - libxcb-dri3-0
      - libdrm2
      - libharfbuzz-icu0
