# --- START OF FILE render.yaml ---

services:
  - type: web
    name: truth-social-scraper # You can name this whatever you like
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    healthCheckPath: "/"
    # The secrets from your Render dashboard will be loaded automatically
    # Pre-install the system packages that Playwright's browser needs to run
    aptPackages:
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libxss1
      - libasound2
      - libpangocairo-1.0-0
      - fonts-liberation
      - libappindicator3-1
      - lsb-release
      - libgbm-dev
