# --- START OF FILE render.yaml ---

services:
  - type: web
    name: truth-social-scraper # This name will appear on your Render dashboard
    env: python
    plan: free # Ensures it uses the free tier
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    healthCheckPath: "/"
    # Pre-install the system packages that Playwright needs to run correctly
    aptPackages:
      - libnss3
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libcups2
      - libxcomposite1
      - libxdamage1
      - libxrandr2
      - libgbm1
      - libxss1
      - libasound2
      - libpangocairo-1.0-0
      - fonts-liberation
      - libappindicator3-1
      - lsb-release
      - libgbm-dev